name: COMMON - DEPLOY
on: [workflow_dispatch]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Stop and remove docker container
              continue-on-error: true
              uses: appleboy/ssh-action@v0.1.2
              with:
                  key: ${{secrets.SSH_KEY}}
                  host: ${{secrets.SSH_HOST}}
                  username: ${{secrets.SSH_USERNAME}}
                  script: |
                      docker stop mcp-common
                      docker rm mcp-common

            - name: Update docker image and run container
              uses: appleboy/ssh-action@v0.1.2
              with:
                  key: ${{secrets.SSH_KEY}}
                  host: ${{secrets.SSH_HOST}}
                  username: ${{secrets.SSH_USERNAME}}
                  script: |
                      docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
                      docker pull ghcr.io/manhattandoctor/mcp-backend/common:latest          
                      docker run -t -i -d -p 31001:31001 -e WEB_PORT=31001 -e LOGGER_LEVEL=3 --name mcp-common ghcr.io/manhattandoctor/mcp-backend/common:latest
