name: TNVED-CODE - BUILD
on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install global dependencies
              run: npm install

            - name: Install local dependencies
              run: npm install --prefix ./src/packages/application/tnved-code

            - name: Build package
              run: npm run build --prefix ./src/packages/application/tnved-code

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Prepare env variables
              run: |
                  echo REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

            - name: Push to GitHub packages
              id: dockerBuild
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  file: ./docker/tnved-code/Dockerfile
                  tags: |
                      ghcr.io/${{ env.REPOSITORY }}/tnved-code:latest
                  labels: |
                      ${{ env.VERSION }}

            - name: Image digest
              run: echo ${{ steps.dockerBuild.outputs.digest }}
